version: '3.8'

services:
  database:
    container_name: db
    restart: always
    build: ./database
    ports:
      - "3306:3306"
    logging:
      driver: none
  server:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "4000:4000"
    links:
      - database